---
- hosts: jenkins
  become: yes
  vars_files:
    - vars.yml

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Add Jenkins repository key
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        state: present

    - name: Add Jenkins repository
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Add jenkins user to docker group
      user:
        name: jenkins
        groups: docker
        append: yes

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Get initial admin password
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_password
      changed_when: false

    - name: Display Jenkins initial admin password
      debug:
        var: jenkins_password.stdout

    - name: Install Jenkins plugins
      jenkins_plugin:
        name: "{{ item }}"
        jenkins_home: "{{ jenkins_home }}"
      with_items:
        - git
        - pipeline
        - docker-pipeline
        - ansible
        - terraform

    - name: Install required system packages
      apt:
        name:
          - python3-pip
          - git
        state: present

    - name: Install AWS CLI
      pip:
        name: awscli
        state: present

    - name: Install Terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755

    - name: Create Jenkins job directory
      file:
        path: "{{ jenkins_home }}/jobs/main-pipeline"
        state: directory
        owner: jenkins
        group: jenkins
        mode: '0755'

    - name: Configure Jenkins job
      copy:
        content: |
          <?xml version='1.1' encoding='UTF-8'?>
          <org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject plugin="workflow-multibranch">
            <actions/>
            <description>Main application pipeline</description>
            <properties/>
            <folderViews/>
            <healthMetrics/>
            <icon class="jenkins.branch.MetadataActionFolderIcon"/>
            <orphanedItemStrategy class="com.cloudbees.hudson.plugins.folder.computed.DefaultOrphanedItemStrategy">
              <pruneDeadBranches>true</pruneDeadBranches>
              <daysToKeep>-1</daysToKeep>
              <numToKeep>-1</numToKeep>
            </orphanedItemStrategy>
            <triggers/>
            <sources class="jenkins.branch.MultiBranchProject$BranchSourceList">
              <data>
                <jenkins.branch.BranchSource>
                  <source class="jenkins.plugins.git.GitSCMSource">
                    <remote>{{ github_repo }}</remote>
                    <credentialsId>github-credentials</credentialsId>
                    <traits>
                      <jenkins.plugins.git.traits.BranchDiscoveryTrait/>
                    </traits>
                  </source>
                </jenkins.branch.BranchSource>
              </data>
            </sources>
            <factory class="org.jenkinsci.plugins.workflow.multibranch.WorkflowBranchProjectFactory"/>
          </org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject>
        dest: "{{ jenkins_home }}/jobs/main-pipeline/config.xml"
        owner: jenkins
        group: jenkins
        mode: '0644'

    - name: Restart Jenkins to apply changes
      service:
        name: jenkins
        state: restarted